### ISSUE TITLE
Chaining with ng-cache-loader / ngtemplate-loader

### ISSUE THREAD

**Issue by ScallyGames** [mogelbrod/apply-loader#2]
When chaining the apply loader with `ng-cache-loader` or `ngtemplate-loader` as described [here](https://github.com/webpack/webpack/issues/940) (the origin of this loader if I understood correctly), these loaders get the original content + `\n\nmodule.exports = module.exports.apply(module, " + json + ")` in string format as its input (from the source this is exactly what this loader does).

`ng-cache-loader` and `ngtemplate-loader` however do not seem to handle this input correctly as they need the pure html string as input.

The way I am currently calling the loaders is `require('ng-cache-loader!apply-loader!jade-loader'!./path/to/template.jade')`

Is this simply wrong usage of this loader or how can I fix this issue.

**Comment by mogelbrod** [comment]
`ng-cache-loader` won't work since it assumes the input is HTML, while `apply-loader` (and most other webpack loaders) work with JS modules.

`ngtemplate-loader` seems to use `html-loader` in [its example](https://github.com/WearyMonkey/ngtemplate-loader#usage) though, which suggests that the following should work:

``` js
require('ngtemplate!apply!jade!./path/to/template.jade')
```

**Comment by ScallyGames** [comment]
Okay.

From [this issue](https://github.com/pugjs/pug-loader/issues/15) I have mistakenly assumed that those two loaders would work together.

What I ended up doing was using `ng-cache-loader` with `jade-html-loader` which works out just fine.

**Comment by mogelbrod** [comment]
You were not mistaken, `ngtemplate` should work using the code example I included in my previous comment, which is also the same as the [comment in your linked issue](https://github.com/pugjs/pug-loader/issues/15#issuecomment-149248913). Did the above not work for you?

**Comment by ScallyGames** [comment]
While `ngtemplate` does work with `apply`, `ng-cache` does not.

Due to some additional options of `ng-cache` is the preferred choice over `ngtemplate` in my case.

**Comment by rkurbatov** [comment]
@mogelbrod chain ngtemplate!apply!jade doesn't work for me:

```
Module parse failed: /home/friedrich/projects/webpack_frontend/node_modules/ngtemplate-loader/index.js!/home/friedrich/projects/webpack_frontend/node_modules/apply-loader/index.js!/home/friedrich/projects/webpack_frontend/node_modules/jade-loader/index.js!/home/friedrich/projects/webpack_frontend/app/components/notification/notification.jade Unexpected token (2:11)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:11)
```

ngtemplate!html!jade-html works just fine at the same time (but it doesn't handles assets requirng)

**Comment by ScallyGames** [comment]
@rkurbatov could you provide your `webpack.config.js`?

**Comment by rkurbatov** [comment]
@Aides359 it is large. If you are interested in:

https://gist.github.com/rkurbatov/c6ac63d5b60ad1a98bbe260c223a646a main config
https://gist.github.com/rkurbatov/234121a983506cad3f167713f8041ba7 loaders

Now jade part is: `test: /app.*\.(pug|jade)$/, loader: 'ngtemplate!html!jade-html'`
I used `test: /app.*\.(pug|jade)$/, loader: 'ngtemplate!apply!jade` without success.

Though current string is working two, I read documentation carefully and found html requires images without need of using explicit require. Just curious how to make apply-loader work in my case.

**Comment by ifokeev** [comment]
We can use `pug-html` with `ngtemplate`.
`pug-html` returns `module.exports = "your_html"` but not the HTML string itself. 

`ngtemplate` has:

```
    if (content.match(/^module\.exports/)) {
        var firstQuote = findQuote(content, false);
        var secondQuote = findQuote(content, true);
        html = content.substr(firstQuote, secondQuote - firstQuote + 1);
    } else {
        html = content;
    }
```

but `ng-cache` hasn't and accepts html only because of:

```
    try {
        source = htmlMinifier.minify(source, extend({}, opts));
    } catch (e) {
        this.emitWarning(e.toString() + '\nUsing unminified HTML');
    }
```

Takes for me about 2 hours to understand what the problem.

The same answer here: https://github.com/bline/jade-html-loader/issues/19#issuecomment-236876532

**Comment by ScallyGames** [comment]
Since my issue is resolved I just closed it.

@rkurbatov: If you still have problems with your config please open another issue (`'ngtemplate!apply!jade` should work however)
